fix env 5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,6 +43,11 @@ jobs:
           TAG="${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'latest' }}"
           echo "TAG=$TAG" >> $GITHUB_ENV
 
+      - name: Show context before Docker build
+        run: |
+          echo "📁 Build context:"
+          ls -la .
+          cat .env.production || echo "❌ .env.production not found!"    
       - name: Checkout code
         uses: actions/checkout@v3
         with:
